<template>
  <UContainer class="py-10 space-y-6">
    <header class="space-y-2">
      <div class="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
        <UIcon name="i-heroicons-clipboard-document-check" class="text-primary" />
        <span class="uppercase tracking-wide">Security · Baseline</span>
      </div>
      <div class="space-y-1">
        <h1 class="text-2xl font-semibold text-gray-900 dark:text-white">
          Security Audit Reports
        </h1>
        <p class="text-gray-600 dark:text-gray-300 max-w-3xl">
          Review the latest security checklist versions and audit outcomes generated by the pipeline.
          The backend populates this list whenever `make security-audit` runs in CI or locally.
        </p>
      </div>
    </header>

    <UCard>
      <template #header>
        <div class="flex flex-wrap items-end gap-3">
          <UFormGroup label="Limit" class="w-full sm:w-32">
            <UInput type="number" min="1" max="200" v-model.number="limit" />
          </UFormGroup>
          <UButton color="primary" :loading="loading" @click="loadReports">
            Refresh
          </UButton>
          <UButton variant="soft" color="gray" @click="openDocs">
            Pipeline Docs
          </UButton>
        </div>
      </template>

      <UTable :rows="rows" :columns="columns" :loading="loading">
        <template #status-data="{ row }">
          <UBadge :color="statusColor(row.status)" size="xs" class="uppercase">
            {{ row.status }}
          </UBadge>
        </template>
        <template #findings-data="{ row }">
          <UButton
            v-if="row.findings"
            size="xs"
            color="gray"
            variant="soft"
            @click="showFindings(row)"
          >
            View JSON
          </UButton>
          <span v-else class="text-gray-400">—</span>
        </template>
        <template #artifactPath-data="{ row }">
          <NuxtLink
            v-if="row.artifactPath"
            :to="row.artifactPath"
            target="_blank"
            class="text-primary underline"
          >
            download
          </NuxtLink>
          <span v-else class="text-gray-400">—</span>
        </template>
      </UTable>

      <div v-if="!loading && !rows.length" class="py-10 text-center text-gray-500 dark:text-gray-400">
        No audit reports recorded yet.
      </div>
    </UCard>

    <UModal v-model:open="findingsOpen">
      <UCard>
        <template #header>
          <div class="flex items-center gap-2">
            <UIcon name="i-heroicons-chart-bar" class="text-primary" />
            <span class="font-semibold">Findings JSON</span>
          </div>
        </template>
        <UCode :code="findingsJson" language="json" class="text-xs" />
        <template #footer>
          <div class="flex justify-end">
            <UButton color="primary" @click="findingsOpen = false">Close</UButton>
          </div>
        </template>
      </UCard>
    </UModal>
  </UContainer>
</template>

<script setup lang="ts">
import type { AuditReport, AuditReportListResponse } from "~/types/security";

const runtimeConfig = useRuntimeConfig();
const router = useRouter();

const limit = ref(20);
const loading = ref(false);
const rows = ref<AuditReport[]>([]);
const findingsOpen = ref(false);
const findingsJson = ref("{}");

const columns = [
  { key: "checklistVersion", label: "Checklist" },
  { key: "status", label: "Status" },
  { key: "initiatedBy", label: "Initiated By" },
  { key: "createdAt", label: "Timestamp" },
  { key: "findings", label: "Findings" },
  { key: "artifactPath", label: "Artifacts" },
];

const mapRow = (report: AuditReport) => ({
  id: report.id,
  baselineId: report.baseline_id,
  initiatedBy: report.initiated_by,
  status: report.status,
  findings: report.findings,
  artifactPath: report.artifact_path,
  sarifPath: report.sarif_path,
  reportHash: report.report_hash,
  checklistVersion: report.checklist_version,
  createdAt: new Date(report.created_at).toLocaleString(),
});

const statusColor = (status: string) => {
  switch (status) {
    case "PASSED":
      return "green";
    case "FAILED":
      return "red";
    case "RUNNING":
      return "orange";
    default:
      return "gray";
  }
};

const loadReports = async () => {
  loading.value = true;
  try {
    const response = await $fetch<AuditReportListResponse>(
      `${runtimeConfig.public.apiBaseUrl}/admin/security/audit-reports`,
      {
        params: { limit: limit.value > 0 ? limit.value : undefined },
        credentials: "include",
      }
    );
    rows.value = (response?.data || []).map(mapRow);
  } catch (err) {
    console.error("Failed to load audit reports", err);
    rows.value = [];
  } finally {
    loading.value = false;
  }
};

const showFindings = (row: AuditReport) => {
  findingsOpen.value = true;
  findingsJson.value = row.findings ? JSON.stringify(row.findings, null, 2) : "{}";
};

const openDocs = () => {
  router.push("/docs/security/audit-pipeline");
};

onMounted(loadReports);
watch(limit, () => {
  loadReports();
});

definePageMeta({
  layout: "embedded",
  title: "AdminSecurityAuditReports",
});
</script>
